version: 2
jobs:
    build:
        working_directory: ~/contentacms
        docker:
            - image: notnoopci/php:7.1.5-browsers
        steps:
            - checkout
    trigger_build:
        working_directory: ~/contentacms
        docker:
            - image: notnoopci/php:7.1.5-browsers
        steps:
            - run: |
                mkdir ~/.ssh
                echo -e "Host *\n  StrictHostKeyChecking no\n  HashKnownHosts no\n  SendEnv LANG LC_*\n" >> ~/.ssh/config
            - run:
                name: Clone demo site repo
                command: git clone git@github.com:contentacms/contenta_jsonapi_demo.git contenta_jsonapi_demo
            - run: cd contenta_jsonapi_demo
            - run:
                name: Add deploy record
                command: echo -e "  * Profile update -> buildNum=[$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL) on [$CIRCLE_PR_REPONAME]($CIRCLE_REPOSITORY_URL)@CIRCLE_SHA1\n" >> DEPLOYS.md
            - run:
                name: Add and commit trigger
                command: |
                    git add DEPLOYS.md
                    git ci -m 'ci(Deploy): Trigger a deploy to the demo site'
                    git push origin master
            - run:
                name: Cleanup
                command: |
                    cd ..
                    rm -fr contenta_jsonapi_demo
workflows:
    version: 2
    deploy_demo_site:
        jobs:
            - build
            - trigger_build:
                requires:
                    - build
                filters:
                    branches:
                        only: 8.x-1.x
